На основании данных таблицы 1 реализовать МНК-алгоритм для 
оценки параметров линейной модели, описывающей статистическую 
зависимость количества зарегистрированных преступлений y от факторов xi: 
x1 – количество безработных, тыс. чел., 
x2 – средняя заработная плата, руб., 
x3 – количество людей, состоящих на учете по алкоголизму, тыс. чел., 
x4 – объем инноваций в области IT, млн. руб., 
x5 – доля населения с доходами ниже прожиточного минимума, % 
x6 – количество разводов, тыс. ед. 
2. Вывести уравнение модели

уравнение модели будет иметь вид

y = θ_0 + θ_1 * x_1 + θ_2 * x2 + θ_3 * x3 + θ_4 * x4 + θ_5 * x5 + θ_6 * x6

необходимо дать оценку параметрам θ_0, θ_1, θ_2, θ_3, θ_4, θ_5, θ_6

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Исходные данные
data = {
    'Год': [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
    'x1': [4922.4, 4130.7, 4137.4, 3889.4, 4263.9, 4243.5, 3966.5, 3657, 3461.2, 4316, 3624.6],
    'x2': [23369, 26629, 29792, 32495, 34030, 36709, 39167, 43724, 47867, 51344, 57244],
    'x3': [1865.9, 1807.9, 1749.5, 1690, 1577, 1444.5, 1304.6, 1208.6, 1126.7, 1102.8, 1077.7],
    'x4': [24951.2, 14648.1, 39558.7, 32365, 46568.8, 27929.6, 37218.5, 51418.1, 116166.5, 126304.8, 159875.4],
    'x5': [12.7, 10.7, 10.8, 11.3, 13.4, 13.2, 12.9, 12.6, 12.3, 12.1, 11],
    'x6': [669.4, 644.1, 668, 693.7, 611.6, 608.3, 611.4, 583.9, 620.7, 564.7, 644.2],
    'y': [2404.8, 2302.2, 2206.2, 2190.6, 2388.5, 2160.1, 2058.5, 1991.5, 2024.3, 2044.2, 2004.4]
}

# Создание DataFrame
df = pd.DataFrame(data)

# Показ первых нескольких строк данных
df.head()


Год      x1     x2      x3       x4    x5     x6       y
0  2011  4922.4  23369  1865.9  24951.2  12.7  669.4  2404.8
1  2012  4130.7  26629  1807.9  14648.1  10.7  644.1  2302.2
2  2013  4137.4  29792  1749.5  39558.7  10.8  668.0  2206.2
3  2014  3889.4  32495  1690.0  32365.0  11.3  693.7  2190.6
4  2015  4263.9  34030  1577.0  46568.8  13.4  611.6  2388.5

In [5]:
# Зависимая переменная
Y = df['y'].values

# Независимые переменные
X = df[['x1', 'x2', 'x3', 'x4', 'x5', 'x6']].values


In [6]:
# Вычисление корреляций
corr_matrix = df.corr()

# Вывов матрицы корреляций
corr_matrix['y']


Год   -0.856197
x1     0.752721
x2    -0.842193
x3     0.875956
x4    -0.635444
x5     0.093171
x6     0.465709
y      1.000000
Name: y, dtype: float64

In [7]:
# Добавим столбец единиц для θ_0
C = np.hstack([np.ones((X.shape[0], 1)), X])
C

array([[1.000000e+00, 4.922400e+03, 2.336900e+04, 1.865900e+03,
        2.495120e+04, 1.270000e+01, 6.694000e+02],
       [1.000000e+00, 4.130700e+03, 2.662900e+04, 1.807900e+03,
        1.464810e+04, 1.070000e+01, 6.441000e+02],
       [1.000000e+00, 4.137400e+03, 2.979200e+04, 1.749500e+03,
        3.955870e+04, 1.080000e+01, 6.680000e+02],
       [1.000000e+00, 3.889400e+03, 3.249500e+04, 1.690000e+03,
        3.236500e+04, 1.130000e+01, 6.937000e+02],
       [1.000000e+00, 4.263900e+03, 3.403000e+04, 1.577000e+03,
        4.656880e+04, 1.340000e+01, 6.116000e+02],
       [1.000000e+00, 4.243500e+03, 3.670900e+04, 1.444500e+03,
        2.792960e+04, 1.320000e+01, 6.083000e+02],
       [1.000000e+00, 3.966500e+03, 3.916700e+04, 1.304600e+03,
        3.721850e+04, 1.290000e+01, 6.114000e+02],
       [1.000000e+00, 3.657000e+03, 4.372400e+04, 1.208600e+03,
        5.141810e+04, 1.260000e+01, 5.839000e+02],
       [1.000000e+00, 3.461200e+03, 4.786700e+04, 1.126700e+03,
        1.161665

In [8]:

# Расчет параметров модели θ с использованием формулы МНК
theta_mnk = np.linalg.inv(C.T @ C) @ (C.T @ Y)

# Вывод значений параметров
theta_mnk


array([ 6.68691295e+01, -8.18896748e-02,  8.72128812e-03,  1.30639160e+00,
        2.34638731e-03,  8.63881753e+01, -1.57694240e+00])

In [9]:
# Прогнозные значения
y_pred = C @ theta_mnk

# Показать прогнозные значения
y_pred


array([2405.24902817, 2265.68699925, 2245.83031295, 2197.76975534,
       2377.07675352, 2173.2062391 , 2025.55280312, 2015.99419827,
       2029.14391194, 2053.06529524, 1986.72470312])

In [17]:
# Среднее значение действительных значений y
y_mean = np.mean(Y)

# Вектор остатков
xi = Y - y_pred

# Вектор отклонений
delta = Y - y_mean

# Показать вектора остатков и отклонений
print("Вектор остатков:", xi)
print("Вектор отклонений от среднего:", delta)


Вектор остатков: [ -0.44902817  36.51300075 -39.63031295  -7.16975534  11.42324648
 -13.1062391   32.94719688 -24.49419827  -4.84391194  -8.86529524
  17.67529688]
Вектор отклонений от среднего: [ 243.40909091  140.80909091   44.80909091   29.20909091  227.10909091
   -1.29090909 -102.89090909 -169.89090909 -137.09090909 -117.19090909
 -156.99090909]


In [11]:
# Вычисление R^2
RSS = xi.T @ xi  # Остаточная сумма квадратов
TSS = delta.T @ delta  # Общая сумма квадратов

R_squared = 1 - (RSS / TSS)

# Вывод коэффициента детерминации
print("Коэффициент детерминации R^2:", R_squared)


Коэффициент детерминации R^2: 0.9767202712600244


задание 3

In [12]:
distribution = {23: 1071, 32: 796, 27: 1263, 26: 980, 44: 1032, 49: 1060, 63: 183, 34: 869, 66: 188, 38: 1006, 28: 1113, 35: 676, 46: 677, 62: 139, 22: 944, 31: 1115, 37: 522, 18: 806, 29: 1340, 30: 734, 20: 910, 69: 202, 36: 1198, 25: 1050, 48: 1026, 40: 723, 21: 716, 45: 690, 41: 837, 24: 810, 19: 971, 67: 128, 42: 978, 33: 758, 57: 136, 47: 831, 43: 820, 55: 62, 51: 188, 39: 695, 52: 193, 56: 76, 60: 266, 64: 189, 61: 226, 16: 236, 15: 53, 58: 262, 50: 150, 53: 47, 65: 79, 59: 74, 71: 85, 14: 49, 17: 126, 70: 26, 73: 17, 54: 26}
import matplotlib.pyplot as plt



In [26]:
df = pd.DataFrame(list(distribution.items()), columns=['Возраст', 'Частота'])

# Замена переменных
df['u'] = df['Возраст']**2
df['v'] = df['Частота']**3

# Печать первых строк данных
df.head()

Возраст  Частота     u           v
0       23     1071   529  1228480911
1       32      796  1024   504358336
2       27     1263   729  2014698447
3       26      980   676   941192000
4       44     1032  1936  1099104768

In [27]:
# Среднее значения переменных
mean_u = np.mean(df['u'])
mean_v = np.mean(df['v'])

# Расчет коэффициентов
numerator_b = np.sum((df['u'] - mean_u) * (df['v'] - mean_v))
denominator_b = np.sum((df['u'] - mean_u) ** 2)
b1 = numerator_b / denominator_b

a1 = mean_v - b1 * mean_u

# Вывод коэффициентов
print("a1 (a):", a1)
print("b1 (b):", b1)


a1 (a): 898794743.9841943
b1 (b): -205521.0576237925


In [28]:
# Предсказанные значения v_pred
v_pred = b1 * df['u'] + a1

# Остаточная сумма квадратов
SSR = np.sum((df['v'] - v_pred) ** 2)

# Общая сумма квадратов
SST = np.sum((df['v'] - mean_v) ** 2)

# Коэффициент детерминации
R_squared = 1 - (SSR / SST)

# Вывод коэффициента детерминации
print("Коэффициент детерминации R^2:", R_squared)


Коэффициент детерминации R^2: 0.2814451591387731


In [16]:
# Возраст и частоты из распределения
x = df['Возраст']
y = df['Частота']

coefficients = np.polyfit(x, y, 3)

polynomial = np.poly1d(coefficients)

x_values = np.linspace(min(x), max(x), 300)
y_values = polynomial(x_values)


print("Коэффициенты полинома:", coefficients)


Коэффициенты полинома: [ 4.71054800e-02 -6.79009085e+00  2.83642355e+02 -2.62999946e+03]


In [ ]:
# x = df['Возраст'].values
# y = df['Частота'].values

# X = np.vstack([np.ones(len(x)), x, x**2, x**3]).T

# # Решение уравнения
# XtX_inv = np.linalg.inv(X.T @ X)
# XtY = X.T @ y
# C = XtX_inv @ XtY

# # коэффициенты полинома
# c0, c1, c2, c3 = C
# print(f'Коэффициенты полинома: c0 = {c0}, c1 = {c1}, c2 = {c2}, c3 = {c3}')
